Repository ahumadamob/springboot-smedico, pull requests merged in 2025-10, with the labels that each got.

#258 tp07-Lucero-Eduardo
  src/main/java/com/imb2025/smedico/controller/EstudioController.java
  src/main/java/com/imb2025/smedico/repository/EstudioRepository.java
  src/main/java/com/imb2025/smedico/service/IEstudioService.java
  src/main/java/com/imb2025/smedico/service/jpa/EstudioServiceImpl.java
Labels: a corregir por el alumno

#248 TP07: Implementación de métodos mágicos en MedicoRepository
  src/main/java/com/imb2025/smedico/controller/MedicoController.java
  src/main/java/com/imb2025/smedico/controller/MedioPagoController.java
  src/main/java/com/imb2025/smedico/repository/MedicoRepository.java
  src/main/java/com/imb2025/smedico/service/IMedicoService.java
  src/main/java/com/imb2025/smedico/service/jpa/MedicoServiceImpl.java
Labels: conflicts

#264 Tp07 araya nicolas
  src/main/java/com/imb2025/smedico/controller/ConsultaController.java
  src/main/java/com/imb2025/smedico/repository/ConsultaRepository.java
  src/main/java/com/imb2025/smedico/service/IConsultaService.java
  src/main/java/com/imb2025/smedico/service/jpa/ConsultaServiceImpl.java
Labels: conflicts

#265 Fix HorarioAtencion response DTO import and usage
  src/main/java/com/imb2025/smedico/controller/HorarioAtencionController.java
  src/main/java/com/imb2025/smedico/repository/ConsultaRepository.java
  src/main/java/com/imb2025/smedico/service/jpa/ConsultaServiceImpl.java
Labels: codex
